//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("The Project")]
[assembly: AssemblyCompany("The Company")]
[assembly: AssemblyCopyright("Copyright 2015 The Company")]
[assembly: AssemblyTrademark("The Trade Mark")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyVersion("0.0.0.0")]
[assembly: AssemblyFileVersion("0.0.0.0")]
[assembly: AssemblyInformationalVersion("Compiled By Erygin.Ale")]


